balena-os/balena-fsl-arm

- layers/meta-resin-fsl-arm/recipes-graphics/cairo/cairo_%.bbappend
We do not need egl or glsev2, as we only use the framebuffer directly.
Signed-off-by: Theodor Gherzan <theodor@resin.io>
@agherzan @floion
> cairo:  Configure without egl glesv2

- CHANGELOG.md
- layers/meta-resin-fsl-arm/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend
Connects to resin-os/meta-resin#133-supervisor-custom-image-tag
@telphan @floion
> Custom docker images in connectable builds on resin-fsl-arm

- solidrun-imx6.coffee
- Discontinue Solidrun/Hummingboard. Other IMX6 boards are already discontinued in this layer.
- Update meta-balena to v2.40.0 for the only board currently in use in this repo: Nitrogen8MM
> Discontinue solidrun/hummingboard

- layers/meta-balena-fsl-arm/recipes-support/resin-init/resin-init-board.bbappend
- layers/meta-balena-fsl-arm/recipes-support/resin-init/resin-init-board/resin-init-board
Add this to board startup to power up the EC21
Changelog-entry: resin-init-board: Add EC21 modem power up sequence
> resin-init-board: Add EC21 modem power up sequence

- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/n8mm-dwe-disable-bootscript-flasher.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/nitrogen8mm-dwe-Use-balenaOS-configs.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-boundary_%.bbappend
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-script-boundary_%.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
u-boot: Set RAM size via cmdline for Nitrogen8MM DWE
u-boot-script: Remove flasher kernel cmdline arg for N8MM DWE, to allow resizing of data partition
even if booted with a generic u-boot
meta-balena: Update to latest revision 2.47.1
> Updates for N8MM DWE

- nitrogen8mm.coffee
The power LED, which is the only one on the board,
does not go off after flashing is completed. Therefore
we need to check the dashboard to see when provisioning
is finished.
Changelog-entry: nitrogen8mm: Update flashing instructions
> nitrogen8mm: Update flashing instructions

- layers/meta-balena-fsl-arm/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
The machines in this repo are still on kernel < 4.15 so let's not use
wireless-regdb-static just yet. When they will use a kernel >= 4.15
let's switch then from crda to wireless-regdb-static.
Changelog-entry: Do not use wireless-regdb-static until we move to kernel >= 4.15
Signed-off-by: Florin Sarbu <florin@balena.io>
> packagegroup-resin-connectivity: Do not use wireless-regdb-static

- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
It was reported that kworker may use more CPU
than expected. Let's update to latest Boundary
kernel HEAD revision to include the fix.
Changelog-entry: linux-boundary: Update to include fix for kworker high CPU
> linux-boundary: Update to include fix for kworker high CPU

- nitrogen8mm-dwe.coffee
USB warning does not appear in dashboard, looks like it
has to do with location of variable definition.
Changelog-entry: nitrogen8mm-dwe: Fix USB warning in dashboard
> nitrogen8mm-dwe: Fix USB warning in dashboard

- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary/imx8mm-sbc-add-no-cqe-for-eMMC.patch
- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
BD recommends disabling CQE for the SBC, just
like HUB3 does, to avoid possible freezes in
case of cqe errors.
linux-boundary: Disable CQE for SBC eMMC
> linux-boundary: Disable CQE for SBC eMMC

- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-boundary_%.bbappend
This revision includes a recommended fix from Boundary for eth PHY reset
issues on the nitrogen8mm-dwe board.
Changelog-entry: u-boot: Bring in fix for eth PHY reset issue
Signed-off-by: Florin Sarbu <florin@balena.io>
> u-boot: Bring in eth PHY reset fix

- nitrogen8mm-dwe.coffee
We do not have yet all the bits and pieces in our infrastructure to
handle this transition at this time so let's make the board public
again.
Changelog-entry: Switch nitrogen8mm-dwe back to public
Signed-off-by: Florin Sarbu <florin@balena.io>
> nitrogen8mm-dwe.coffee: Switch board back to public

- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/bootscript-n8mm-allow-flashing-balenaOS.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/bootscript-n8mm-dwe-Integrate-with-BalenaOS.patch
Even if we now load the dtb from the rootfs and default to
the boot partition if not found, but we should continue to load
it from the boot partition if the board is booted with
a stock u-boot, like in the case of a flasher image on a
board that never ran Balena.
Changelog-entry: u-boot-script: Continue to boot flasher images with stock uboot
> u-boot-script: Continue to boot flasher images with stock uboot

- layers/meta-balena-fsl-arm/recipes-core/systemd/systemd_%.bbappend
Removal of audit sockets to disable audit messages should
be done in meta-balena.
Changelog-entry: recipes-core/systemd: Move audit socket removal to meta-balena
> recipes-core/systemd: Move audit socket removal to meta-balena

- layers/meta-balena-fsl-arm/conf/samples/bblayers.conf.sample
Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers: Modify layer ordering

- layers/meta-balena-fsl-arm/conf/samples/bblayers.conf.sample
Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> bblayers.conf.sample: add meta-perl

- layers/meta-balena-fsl-arm/conf/layer.conf
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image-initramfs.bbappend
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image.inc
- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
As of right now the kernel no longer fits in the rootfs, we need to make some more space and make sure ROOTFS_SIZE is not set by the BSP
> Optimize build for size

- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
Currently balenaOS disables DEFAULT_SECURITY_APPARMOR due to containers failing to start with missing dependencies.
The BSP enables CONFIG_SECURITY_APPARMOR and the final result is apparmor enabled although disabled from meta-balena.
Changelog-entry: ensure apparmor is disabled
> linux-boundary: Ensure apparmor is disabled

- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/0002-fix-return-vaue-propagatin-out-of-environ.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/0003-add-imx8mm-resin-hooks.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-imx_%.bbappend
- layers/meta-balena-fsl-arm/recipes-containers/balena-supervisor/balena-supervisor.bbappend
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image.inc
Changelog-entry: Set imx8mm-lpddr4-evk LED for indication
> balena-supervisor: Set imx8mm-lpddr4-evk LED for indication

- .gitmodules
The branches are used by renovate when updating submodules to the latest branch head.
Changelog-entry: update git submodule branches
> .gitmodules: update branches

- layers/meta-balena-fsl-arm/recipes-connectivity/bluetooth-scripts/files/nitrogen8mm-hci.service
The path for testing when the UART device has been attached to the Bluez stack changed again in the new kernel.
Changelog-entry: Fix bluetooth on new kernel for nitrogen8mm
> bluetooth-scripts: Fix bluetooth on new kernel for nitrogen8mm

- .github/workflows/nitrogen8mm-dwe.yml
This enables using the flasher image in testing, while still deploying the non flasher
Changelog-entry: Allow overriding default test image
requires: https://github.com/balena-os/balena-yocto-scripts/pull/555 - pinned action to that branch for debugging - ensure that this is put back before merge
HUP suite disabled due to needing modifications to leviathan to support it, including: https://github.com/balena-os/leviathan/issues/1286
> Allow overriding default test image

- layers/meta-balena-fsl-arm/recipes-connectivity/bluetooth-scripts/bluetooth-scripts.bb
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-bdsdmac_git.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-cypress_git.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-gslx680_1.0.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-sx-pceac2_git.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
This PR fixes the errors encountered when building with balenaOS v6.5.30, which enables usrmerge
> Fix usrmerge builds

- emgw3.coffee
For automated testing we need to use the flasher image to provision the board. The customer will keep using the internal image for provisioning, which is the image that will continue to be offered in the dashboard.
Changelog-entry: Specify in the coffee file what is the flasher image for emgw3
> emgw3.coffee: Specify the flasher artifact

- .github/workflows/nitrogen8mm.yml
This stops an issue in the yocto-scripts workflow logic caused by get_inputs running twice on commits
Changelog-entry: workflows: stop get_inputs job running on both PR and PRT triggers
> workflows: stop get_inputs job running on both PR and PRT triggers
