- CHANGELOG.md
- cubox-i.coffee
- nitrogen6x.coffee
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-fsl-arm/2)
> Promote boards to released

- layers/meta-resin-fsl-arm/recipes-kernel/linux/linux-fslc_%.bbappend
@agherzan @floion
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-fsl-arm/3)
> Hotfix Cubox-i kernel

- .gitmodules
- layers/meta-resin-fsl-arm/conf/samples/bblayers.conf.sample
> Switch to docker

- CHANGELOG.md
- layers/meta-resin-fsl-arm/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
> BCM4330/BCM4329 support on cubox-i

- CHANGELOG.md
- layers/meta-resin-fsl-arm/conf/samples/local.conf.sample
> Improve build disk usage

- CHANGELOG.md
- layers/meta-resin-fsl-arm/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg
> Replace SUPERVISOR_TAG by TARGET_TAG on resin-fsl-arm

- CHANGELOG.md
- layers/meta-resin-fsl-arm/conf/samples/local.conf.sample
Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg
> Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-fsl-arm

- .gitmodules
- cubox-i.coffee
- nitrogen6x.coffee
This implements resin-os/resin-yocto-scripts#31
Signed-off-by: Eugene Mirotin eugene@resin.io
@agherzan @floion
> Update to use the simplified JSON building process on resin-fsl-arm

- CHANGELOG.md
- cubox-i.coffee
- nitrogen6x.coffee
@agherzan @michal-mazurek @telphan
> Switch partition with conf in coffee

- CHANGELOG.md
- layers/meta-resin-fsl-arm/conf/samples/local.conf.sample
@agherzan @floion 
Connects to resin-os/meta-resin#315
> Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

- CHANGELOG.md
- layers/meta-resin-fsl-arm/conf/samples/bblayers.conf.sample
Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek
> Add meta-filesystem as we need aufs-utils on resin-fsl-arm

- README.md
Connects to contributing
@telphan @floion @michal-mazurek
> Add Contributing section on resin-fsl-arm

- CHANGELOG.md
> * Update resin-yocto-scripts to fix logging in container builds on resin-fsl-arm

- CHANGELOG.md
Signed-off-by: Florin Sarbu <florin@resin.io>
> v2.15.1+rev1

- nitrogen6x.coffee
Changelog-entry: nitrogen6x.coffee: Update yocto version to rocko
Signed-off-by: Sebastian Panceac <sebastian@resin.io>
> nitrogen6x.coffee: Update yocto version to rocko

- layers/meta-balena-fsl-arm/recipes-connectivity/bluetooth-scripts/files/nitrogen8mm-hci.service
- layers/meta-balena-fsl-arm/recipes-kernel/linux/linux-boundary_%.bbappend
- Address https://github.com/balena-os/balena-fsl-arm/issues/84
- Bring in latest commit from https://github.com/boundarydevices/linux-imx6/commits/boundary-imx_4.14.x_2.0.0_ga
> Update kernel, disable cqe

- nitrogen8mm-dwe.coffee
- nitrogen8mm.coffee
Changelog-entry: Set private to false in .coffee files for the public device types
Signed-off-by: Florin Sarbu <florin@balena.io>
> .coffee: Set private to false for the public device types

- layers/meta-balena-fsl-arm/recipes-connectivity/networkmanager/networkmanager_%.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/kernel-modules/kernel-module-qcacld_git.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-bdsdmac_git.bbappend
Addresses https://github.com/balena-os/balena-fsl-arm/issues/100
> Switch sbc dr, fw, update to v2.51.1

- layers/meta-balena-fsl-arm/conf/layer.conf
- layers/meta-balena-fsl-arm/conf/samples/bblayers.conf.sample
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-script-boundary_%.bbappend
- layers/meta-balena-fsl-arm/recipes-kernel/linux-firmware/linux-firmware-bdsdmac_git.bbappend
- nitrogen8mm-dwe.coffee
- nitrogen8mm.coffee
Also addresses tcpdump issue - https://github.com/balena-os/balena-fsl-arm/issues/100
> Switch to warrior, systemd 241, add sbc wifi fw fix

- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/0001-nitrogen8mm-Use-balenaOS-configs.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/nitrogen8mm-dwe-1g-Use-BalenaOS-configs.patch
Update meta-balena from 2.65.0 to 2.67.3
Changelog-entry: Update meta-balena from v2.65.0 to v2.67.3
> layers/meta-balena: Update to v2.67.3

- layers/meta-balena-fsl-arm/conf/samples/local.conf.sample
- layers/meta-balena-fsl-arm/recipes-bsp/imx-mkimage/imx-boot_%.bbappend
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/nitrogen-resin-specific-env-integration-kconfig.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/nitrogen6x-resin-specific-env-integration-kconfig.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-boundary_%.bbappend
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image-flasher.bbappend
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image.bbappend
- layers/meta-balena-fsl-arm/recipes-core/images/balena-image.inc
- layers/meta-balena-fsl-arm/recipes-core/images/resin-image-flasher.bbappend
- nitrogen6x.coffee
- nitrogen6xq2g.coffee
- nitrogen8mm-dwe.coffee
- nitrogen8mm.coffee
- solidrun-imx6.coffee
Rename resin image types to balena and replace RESIN_ env vars
Changelog-entry: Rename resin image types to balena
Signed-off-by: Kyle Harding <kyle@balena.io>
> balena-fsl-arm: Rename resin image types to balena

- .github/workflows/nitrogen8mm.yml
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/files/bootscript-n8mm-allow-flashing-balenaOS.patch
- layers/meta-balena-fsl-arm/recipes-bsp/u-boot/u-boot-boundary_%.bbappend
- layers/meta-balena-fsl-arm/recipes-support/hostapp-update-hooks/files/98-update-imx-boot
- layers/meta-balena-fsl-arm/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend
Adds kernel dtb overlap checks & fixes and replaces https://github.com/balena-os/balena-fsl-arm/pull/718
> Nitrogen8MM: run automated testing for SBC

- .gitmodules
- layers/meta-balena-fsl-arm/conf/samples/bblayers.conf.sample
- layers/meta-balena-fsl-arm/conf/samples/local.conf.sample
https://balena.fibery.io/Work/Project/balenaos-SBOM-as-release-asset-1515
> Add CycloneDX SBOM and VEX generation
